/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

/**
 *
 * @author Aluno
 */
public class frmPrincipalVIEW extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipalVIEW
     */
    public frmPrincipalVIEW() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMenu1 = new javax.swing.JMenu();
        menuFuncionario = new javax.swing.JMenu();
        menuProduto = new javax.swing.JMenu();
        menuSetor = new javax.swing.JMenu();
        menuMarca = new javax.swing.JMenu();
        menuCor = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        menuEditarFuncionario = new javax.swing.JMenu();
        menuEditarProduto = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("PRINCIPAL");

        JMenu1.setText("Cadastrar");

        menuFuncionario.setText("Funcionario");
        menuFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuFuncionarioMouseClicked(evt);
            }
        });
        JMenu1.add(menuFuncionario);

        menuProduto.setText("Produto");
        menuProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuProdutoMouseClicked(evt);
            }
        });
        JMenu1.add(menuProduto);

        menuSetor.setText("Setor");
        menuSetor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSetorMouseClicked(evt);
            }
        });
        JMenu1.add(menuSetor);

        menuMarca.setText("Marca");
        menuMarca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMarcaMouseClicked(evt);
            }
        });
        JMenu1.add(menuMarca);

        menuCor.setText("Cor");
        menuCor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCorMouseClicked(evt);
            }
        });
        JMenu1.add(menuCor);

        jMenuBar1.add(JMenu1);

        jMenu2.setText("Editar");

        menuEditarFuncionario.setText("Funcionario");
        menuEditarFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuEditarFuncionarioMouseClicked(evt);
            }
        });
        jMenu2.add(menuEditarFuncionario);

        menuEditarProduto.setText("Produto");
        menuEditarProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuEditarProdutoMouseClicked(evt);
            }
        });
        jMenu2.add(menuEditarProduto);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(212, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(424, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuFuncionarioMouseClicked
        frmCadFuncionarioVIEW objfrmcadfuncionarioview = new frmCadFuncionarioVIEW();
        objfrmcadfuncionarioview.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_menuFuncionarioMouseClicked

    private void menuProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuProdutoMouseClicked
        frmCadProdutoVIEW objfrmcadprodutoview = new frmCadProdutoVIEW();
        objfrmcadprodutoview.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_menuProdutoMouseClicked

    private void menuSetorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSetorMouseClicked
        frmCadSetorVIEW objfrmcadsetorview = new frmCadSetorVIEW();
        objfrmcadsetorview.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_menuSetorMouseClicked

    private void menuMarcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMarcaMouseClicked
        frmCadMarcaVIEW objfrmcadmarcaview = new frmCadMarcaVIEW();
        objfrmcadmarcaview.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_menuMarcaMouseClicked

    private void menuCorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCorMouseClicked
        frmCadCorVIEW objfrmcadcorview = new frmCadCorVIEW();
        objfrmcadcorview.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_menuCorMouseClicked

    private void menuEditarFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuEditarFuncionarioMouseClicked
        frmEditarFuncionarioVIEW objfrmeditarfuncionarioview = new frmEditarFuncionarioVIEW();
        objfrmeditarfuncionarioview.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_menuEditarFuncionarioMouseClicked

    private void menuEditarProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuEditarProdutoMouseClicked
        frmEditarProdutoVIEW objfrmeditarprodutoview = new frmEditarProdutoVIEW();
        objfrmeditarprodutoview.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_menuEditarProdutoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipalVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMenu1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuCor;
    private javax.swing.JMenu menuEditarFuncionario;
    private javax.swing.JMenu menuEditarProduto;
    private javax.swing.JMenu menuFuncionario;
    private javax.swing.JMenu menuMarca;
    private javax.swing.JMenu menuProduto;
    private javax.swing.JMenu menuSetor;
    // End of variables declaration//GEN-END:variables
}
